server:
  port: 8191
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GautamChaursia/spring-cloud-config-store
          search-paths:
          - '*service'
